version: '3'

services:
  db:
    build: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"

  wordpress:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./wp-content:/var/www/html/wp-content
    depends_on:
      - db
